### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by cdslxc** [LottieFiles/svelte-lottie-player#11]
I got a warning that` document is not defined` in my terminal.

I'm using SvelteKit.

```js
<script lang="ts">
	//@ts-ignore
	import { LottiePlayer } from '@lottiefiles/svelte-lottie-player';
</script>

<LottiePlayer
	  src="/checkmark.json"
	  autoplay={true}
	  loop={true}
	  renderer="svg"
	  background="transparent"
	  height={600}
	  width={600}
/>
```

<img width="871" alt="CleanShot 2022-09-12 at 04 02 23@2x" src="https://user-images.githubusercontent.com/8092790/189548738-f5958646-5c85-486f-9f2b-b93e13526c0f.png">

**Comment by secondl1ght** [comment]
See issue #7

**Comment by cdslxc** [comment]
Duplicate.
